[package]
name = "init"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "init"
path = "src/main.rs"

[dependencies]
nix = { version = "0.27", features = ["process", "fs", "mount"] }
libc = "0.2"
ternary-core = { path = "../ternary-core" }
