[workspace]

[package]
name = "desktop-metal"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "desktop-metal"
path = "src/main.rs"

[profile.dev]
panic = "abort"
opt-level = 2

[dependencies]
libm = { version = "0.2", default-features = false }

[profile.release]
panic = "abort"
strip = false
debug = 2
