#!/usr/bin/env python3
# Rasterize a clean sans-serif TTF into anti-aliased grayscale coverage atlases
# and emit desktop-metal/src/font_aa.rs. Two sizes: small (body/chrome) and large
# (hero/headings). The bare-metal renderer alpha-blends the coverage over the
# framebuffer — smooth proportional type instead of the 8x8 "Minecraft" bitmap.
#
# Run on the host (needs Pillow). Output is committed so the no_std build is clean.
import sys
from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf"
OUT  = "desktop-metal/src/font_aa.rs"
FIRST, LAST = 0x20, 0x7E  # printable ASCII

def build(px):
    font = ImageFont.truetype(FONT, px)
    asc, desc = font.getmetrics()
    line = asc + desc
    pad = px
    base = px * 2
    cov = bytearray()
    glyphs = []  # (off,w,h,adv,bx,top)
    for c in range(FIRST, LAST + 1):
        ch = chr(c)
        adv = round(font.getlength(ch))
        img = Image.new("L", (px * 3, px * 3), 0)
        d = ImageDraw.Draw(img)
        d.text((pad, base), ch, font=font, fill=255, anchor="ls")
        bbox = img.getbbox()
        if bbox is None:
            glyphs.append((len(cov), 0, 0, adv, 0, 0))
            continue
        l, t, r, b = bbox
        w, h = r - l, b - t
        crop = img.crop(bbox)
        off = len(cov)
        cov.extend(crop.tobytes())
        bx = l - pad
        top = base - t  # rows from baseline up to glyph top
        glyphs.append((off, w, h, adv, bx, top))
    return asc, line, cov, glyphs

def emit(f, tag, asc, line, cov, glyphs):
    f.write(f"pub const ASCENT_{tag}: i32 = {asc};\n")
    f.write(f"pub const LINE_{tag}: i32 = {line};\n")
    f.write(f"pub static COV_{tag}: [u8; {len(cov)}] = [")
    f.write(",".join(str(b) for b in cov))
    f.write("];\n")
    f.write(f"pub static GLYPHS_{tag}: [Glyph; {len(glyphs)}] = [\n")
    for (off, w, h, adv, bx, top) in glyphs:
        f.write(f"    Glyph {{ off: {off}, w: {w}, h: {h}, adv: {adv}, bx: {bx}, top: {top} }},\n")
    f.write("];\n\n")

def main():
    sizes = {"T": 13, "S": 16, "L": 30}
    with open(OUT, "w") as f:
        f.write("// AUTO-GENERATED by scripts/gen_font_aa.py — do not edit by hand.\n")
        f.write("// Anti-aliased proportional font (Ubuntu Sans) as grayscale coverage.\n\n")
        f.write("pub struct Glyph { pub off: u32, pub w: u8, pub h: u8, pub adv: u8, pub bx: i8, pub top: i8 }\n\n")
        for tag, px in sizes.items():
            asc, line, cov, glyphs = build(px)
            emit(f, tag, asc, line, cov, glyphs)
            print(f"[{tag}] px={px} ascent={asc} line={line} cov={len(cov)}B glyphs={len(glyphs)}", file=sys.stderr)

if __name__ == "__main__":
    main()
